clone:
  git:
    image: woodpeckerci/plugin-git:latest
    settings:
      recursive: false
      depth: 0

steps:
  build:
    image: ghcr.io/gohugoio/hugo:latest
    commands:
      - git config --global --add safe.directory /woodpecker/src/github.com/thoufix/obsidian-blog-pipeline
      - git submodule update --init --recursive
      - cd hugo-site
      - hugo --minify

  deploy:
    image: alpine:latest
    volumes:
      - /srv/blog:/srv/blog
    commands:
      - rm -rf /srv/blog/public/*
      - cp -r hugo-site/public/* /srv/blog/public/
