name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - 'hugo-site/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build site with Hugo
        run: |
          cd hugo-site
          hugo --minify --environment production

      - name: Deploy to web directory
        run: |
          # Remove old files and copy new build
          sudo rm -rf /var/www/blog/public/*
          sudo cp -r hugo-site/public/* /var/www/blog/public/
          sudo chown -R www-data:www-data /var/www/blog/
          echo "Deployment complete to /var/www/blog/public/!"