name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - 'hugo-site/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          
      - name: Build site with Hugo
        run: |
          cd hugo-site
          hugo --minify --environment production --baseURL "https://blog.pilab.space/"
          
      - name: Deploy to web directory
        run: |
          # Sync built site into Nginx root
          sudo rsync -av --delete hugo-site/public/ /var/www/blog/
          sudo chown -R www-data:www-data /var/www/blog/
          echo "✅ Deployment complete to /var/www/blog/!"
