name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - 'hugo-site/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build site with Hugo
        run: |
          cd hugo-site
          hugo --minify

      - name: Deploy to web directory
        run: |
          # Copy built site to web server directory
          sudo cp -r hugo-site/public/* /var/www/hugo-site/
          sudo chown -R www-data:www-data /var/www/hugo-site/
          echo "Deployment complete!"